export interface TripMaster {
  id: string;
  name: string;
  slug: string;
  short_description?: string;
  long_description?: string;
  highlights?: string[];
  destinations?: string[];
  countries?: string[];
  duration_days?: number;
  duration_nights?: number;
  base_price_cents?: number;
  base_price_currency: string;
  single_supplement_cents?: number;
  inclusions?: Record<string, unknown>[];
  exclusions?: Record<string, unknown>[];
  difficulty_level?: number;
  age_min?: number;
  age_max?: number;
  tags?: string[];
  hero_image_urls?: string[];
  gallery_urls?: string[];
  status: string;
  trip_type?: string;
  visa_requirements?: Record<string, unknown>[];
  packing_list_template?: Record<string, unknown>;
  terms_version?: string;
  created_by?: string;
  created_at: string;
  updated_at: string;
  cancellation_policy?: Record<string, unknown>;
  insurance_mandatory: boolean;
  fitness_level_required?: number;
  best_seasons?: string[];
  group_size_min?: number;
  group_size_max?: number;
  meta_title?: string;
  meta_description?: string;
  featured: boolean;
  display_order: number;
  faqs?: Record<string, unknown>;
  fitness_requirements?: string;
  altitude_details?: string;
  weather_notes?: string;
  whats_included_text?: string;
  whats_excluded_text?: string;
}
